spring.application.name=school

spring.datasource.url=jdbc:postgresql://localhost:5432/school
spring.datasource.username=postgres
spring.datasource.password=271021

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true