spring.application.name=parkinglot

spring.datasource.url=jdbc:postgresql://localhost:5432/parkingLot
spring.datasource.username=postgres
spring.datasource.password=271021

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true